### ISSUE TITLE
Cooldown breaks if the cooldown is changed

### ISSUE THREAD

**Issue by aetaric** [Fluzzarn/Fluzzbot#6]
fluzzbot: I'm on cooldown for another -293 seconds

**Comment by Fluzzarn** [comment]
Fixed in [6b061f](https://github.com/Fluzzarn/Fluzzbot/commit/6b061f9994d0e7f84df7b1d7ef295d5d715fb0b8), when setcd first inserted a command into the table, the wrong parameter was being passed in, causing it to always be 0
